In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'taxis',
 'tips',
 'titanic']

In [3]:
df = sns.load_dataset("diamonds")
df

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [4]:
df[["carat", "depth", "price", "x", "y", "z"]]

carat  depth  price     x     y     z
0       0.23   61.5    326  3.95  3.98  2.43
1       0.21   59.8    326  3.89  3.84  2.31
2       0.23   56.9    327  4.05  4.07  2.31
3       0.29   62.4    334  4.20  4.23  2.63
4       0.31   63.3    335  4.34  4.35  2.75
...      ...    ...    ...   ...   ...   ...
53935   0.72   60.8   2757  5.75  5.76  3.50
53936   0.72   63.1   2757  5.69  5.75  3.61
53937   0.70   62.8   2757  5.66  5.68  3.56
53938   0.86   61.0   2757  6.15  6.12  3.74
53939   0.75   62.2   2757  5.83  5.87  3.64

[53940 rows x 6 columns]

In [5]:
diamond = np.array(df[["carat", "depth", "price", "x", "y", "z"]])
diamond

array([[2.300e-01, 6.150e+01, 3.260e+02, 3.950e+00, 3.980e+00, 2.430e+00],
       [2.100e-01, 5.980e+01, 3.260e+02, 3.890e+00, 3.840e+00, 2.310e+00],
       [2.300e-01, 5.690e+01, 3.270e+02, 4.050e+00, 4.070e+00, 2.310e+00],
       ...,
       [7.000e-01, 6.280e+01, 2.757e+03, 5.660e+00, 5.680e+00, 3.560e+00],
       [8.600e-01, 6.100e+01, 2.757e+03, 6.150e+00, 6.120e+00, 3.740e+00],
       [7.500e-01, 6.220e+01, 2.757e+03, 5.830e+00, 5.870e+00, 3.640e+00]])

In [6]:
diamond[0]

array([2.30e-01, 6.15e+01, 3.26e+02, 3.95e+00, 3.98e+00, 2.43e+00])

In [7]:
diamond[0:2]

array([[2.30e-01, 6.15e+01, 3.26e+02, 3.95e+00, 3.98e+00, 2.43e+00],
       [2.10e-01, 5.98e+01, 3.26e+02, 3.89e+00, 3.84e+00, 2.31e+00]])

In [8]:
diamond[100:105]

array([[7.50e-01, 6.32e+01, 2.76e+03, 5.80e+00, 5.75e+00, 3.65e+00],
       [7.50e-01, 5.99e+01, 2.76e+03, 6.00e+00, 5.96e+00, 3.58e+00],
       [7.40e-01, 6.16e+01, 2.76e+03, 5.80e+00, 5.85e+00, 3.59e+00],
       [7.50e-01, 6.17e+01, 2.76e+03, 5.85e+00, 5.79e+00, 3.59e+00],
       [8.00e-01, 6.29e+01, 2.76e+03, 5.94e+00, 5.87e+00, 3.72e+00]])

In [9]:
diamond[-10:-5]

array([[7.100e-01, 6.050e+01, 2.756e+03, 5.790e+00, 5.740e+00, 3.490e+00],
       [7.100e-01, 5.980e+01, 2.756e+03, 5.740e+00, 5.730e+00, 3.430e+00],
       [7.000e-01, 6.050e+01, 2.757e+03, 5.710e+00, 5.760e+00, 3.470e+00],
       [7.000e-01, 6.120e+01, 2.757e+03, 5.690e+00, 5.720e+00, 3.490e+00],
       [7.200e-01, 6.270e+01, 2.757e+03, 5.690e+00, 5.730e+00, 3.580e+00]])

In [10]:
diamond[:,0]

array([0.23, 0.21, 0.23, ..., 0.7 , 0.86, 0.75])

In [11]:
diamond[0:2, 0:3]

array([[2.30e-01, 6.15e+01, 3.26e+02],
       [2.10e-01, 5.98e+01, 3.26e+02]])

In [12]:
diamond[0:2,1]

array([61.5, 59.8])

In [13]:
diamond[0, ::2]

array([2.30e-01, 3.26e+02, 3.98e+00])

In [14]:
diamond[:,0].reshape(-1,1)

array([[0.23],
       [0.21],
       [0.23],
       ...,
       [0.7 ],
       [0.86],
       [0.75]])

In [15]:
carat1 = diamond[:,0].reshape(len(diamond),1)
carat1

array([[0.23],
       [0.21],
       [0.23],
       ...,
       [0.7 ],
       [0.86],
       [0.75]])

In [16]:
depth = diamond[:,1].reshape(len(diamond),1)
depth

array([[61.5],
       [59.8],
       [56.9],
       ...,
       [62.8],
       [61. ],
       [62.2]])

In [17]:
np.concatenate([carat1,depth],axis=1)

array([[ 0.23, 61.5 ],
       [ 0.21, 59.8 ],
       [ 0.23, 56.9 ],
       ...,
       [ 0.7 , 62.8 ],
       [ 0.86, 61.  ],
       [ 0.75, 62.2 ]])

In [18]:
xyz = diamond[:,-3:].reshape(len(diamond),3)
xyz

array([[3.95, 3.98, 2.43],
       [3.89, 3.84, 2.31],
       [4.05, 4.07, 2.31],
       ...,
       [5.66, 5.68, 3.56],
       [6.15, 6.12, 3.74],
       [5.83, 5.87, 3.64]])

In [19]:
xyz[:,0]

array([3.95, 3.89, 4.05, ..., 5.66, 6.15, 5.83])

In [20]:
volume = xyz[:,0] * xyz[:,1] * xyz[:,2]
volume.reshape(len(volume), 1)

array([[ 38.20203 ],
       [ 34.505856],
       [ 38.076885],
       ...,
       [114.449728],
       [140.76612 ],
       [124.568444]])