In [1]:
import numpy as np

In [ ]:
# axis 1 = y axis, column, feature
# axis 0 = x axis, row, observation

In [2]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [3]:
a.dtype

dtype('int32')

In [4]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [18]:
aa = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.int32)
bb = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)

print(aa.itemsize)  # bytesize of each elements
print(bb.itemsize)  # bytesize of each elements

4
8


In [19]:
arr = np.array([[1, 2], [3, 4], [5, 6]], dtype=complex)
arr

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [20]:
arr1 = np.array([1, 2, 3], dtype=int)
print(arr1.dtype)

arr2 = arr1.astype(np.float64) 
print(arr2, arr2.dtype)

int32
[1. 2. 3.] float64


In [22]:
arr3 = np.array([8.75, 5.9, 10.445])
print(arr3)

arr4 = arr3.astype(np.int32)
print(arr4)

[ 8.75   5.9   10.445]
[ 8  5 10]


In [2]:
np.array([1, 2, 3], ndmin=3, dtype=complex)

array([[[1.+0.j, 2.+0.j, 3.+0.j]]])

In [3]:
x  = np.arange(3.)
np.array2string(x, formatter={'float_kind':lambda x: "%.2f" % x})

'[0.00 1.00 2.00]'

In [4]:
x  = np.arange(3)
np.array2string(x, formatter={'int':lambda x: hex(x)})

'[0x0 0x1 0x2]'

In [5]:
np.array_str(np.arange(3))

'[0 1 2]'

In [6]:
# Return an array converted to a float type.

print(np.asfarray([2, 3]))

print(np.asfarray([2, 3], dtype='float'))

print(np.asfarray([2, 3], dtype='int8'))

[2. 3.]
[2. 3.]
[2. 3.]


### <i><b>numpy.arange:</b> 
    
.return evenly spaced values within a given interval.

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(5.0), np.arange(5.0).dtype

(array([0., 1., 2., 3., 4.]), dtype('float64'))

In [9]:
np.arange(-4,6)

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [10]:
np.arange(-4, 6, 0.5)

array([-4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,
        1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5])

In [51]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [52]:
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [53]:
a2.shape

(1, 6)

### <i><b>numpy.zeros, ones, eye, full, etc.

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros((3, 2, 4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [38]:
np.zeros((4, 3), dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [39]:
np.zeros((4, 3), dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [40]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.ones((2,4))+7

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [42]:
np.ones((2,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [43]:
np.ones((2,4))/0

C:\Users\TR\AppData\Local\Temp/ipykernel_7316/4236025466.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.ones((2,4))/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [44]:
arr1 = np.zeros(7)
arr2 = np.ones(7)

arr1, arr2

(array([0., 0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1., 1.]))

In [45]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
np.full(4, "legend")

array(['legend', 'legend', 'legend', 'legend'], dtype='<U6')

In [48]:
np.full((3,32,32),255)

array([[[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]]])

In [49]:
np.full((2, 2), [1, 2])

array([[1, 2],
       [1, 2]])

In [ ]:
# numpy.empty : Return a new array of given shape and type, without initializing entries.

In [54]:
np.empty(2)

array([0.59253624, 0.58407554])

In [55]:
np.empty([2, 2], dtype=int)

array([[-1902911991,  1071838734],
       [  812435912,  1071820991]])

In [6]:
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.pad(arr, pad_width=1, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

### <i><b>numpy.linspace: 

. Return evenly spaced numbers over a specified interval. Default number is 50.<br>
. it is used for lineer sequences

In [11]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [12]:
np.linspace(1,10,dtype=int)

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [13]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [15]:
np.linspace(1,10,3, endpoint=False)

array([1., 4., 7.])

In [16]:
np.linspace(0,10,15,dtype=bool)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [17]:
np.linspace(25, 45, 6, dtype=int)
# it is useful when you want to convert numeric data to categorical type

array([25, 29, 33, 37, 41, 45])

## random

.<b>np.random.random</b>    : Return random floats in the half-open interval [0.0, 1.0)<br>

.<b>np.random.rand</b>      : Create an array of the given shape and populate it with random samples from a "uniform distribution" over [0, 1).<br>

.<b>np.random.randn</b>     : Return a sample (or samples) from the “standard normal” distribution.<br>

.<b>np.random.randint</b>   : Return random integers from low (inclusive) to high (exclusive). 
                       Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open”                        interval [low, high).
                     
.<b>np.random.normal</b>    : Draw random samples from a normal (Gaussian) distribution.

In [23]:
np.random.random(2)
# random() takes at most 1 positional argument

array([0.13391719, 0.27778256])

In [24]:
10*np.random.random(3)

array([9.21909388, 9.08884652, 1.69027954])

In [3]:
np.random.rand(3,2)
# random samples from a "uniform distribution" over [0, 1).

array([[0.26254269, 0.73306053],
       [0.70268653, 0.07448949],
       [0.44644726, 0.11181994]])

In [25]:
np.random.randn(2)

array([0.59253624, 0.58407554])

In [2]:
np.random.randn(5,5)
# produces numbers between -3 / 3 (standard deviation of normal distribution) 

array([[ 0.48554615,  1.31049514,  0.32942306,  1.48766045, -0.00742688],
       [ 0.50008728, -0.40291274,  0.25524734,  1.0729652 , -0.07789082],
       [ 1.67579801, -0.64883556,  0.67796872,  0.09779988,  0.3490775 ],
       [ 0.0385554 , -2.18677004,  0.51362472,  0.86689545,  1.68185387],
       [-0.99812132, -0.32019139, -0.36325253, -0.44041566,  0.83681088]])

In [26]:
np.random.randn(2,2,3)


array([[[ 0.48902617, -0.0545903 , -1.17525231],
        [-0.24129179,  0.79145206,  0.48099393]],

       [[-1.18548794,  0.05805062,  1.34367833],
        [-0.74799746,  1.09328564,  0.32116856]]])

In [27]:
np.random.randint(2, size=10)

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1])

In [4]:
np.random.randint(0,10,6)

array([1, 0, 6, 3, 3, 0])

In [28]:
np.random.randint(20,80, size=(3,2,5))

array([[[73, 43, 34, 24, 34],
        [55, 23, 29, 43, 23]],

       [[56, 23, 40, 53, 37],
        [23, 25, 75, 55, 48]],

       [[30, 48, 46, 42, 66],
        [35, 45, 30, 70, 50]]])

In [31]:
np.random.randint(1, [3, 5, 10])

array([2, 4, 8])

In [32]:
np.random.randint([1, 5, 7], 10)

array([7, 9, 8])

In [5]:
np.random.randint([18,60,160,0],  # low   # like ordinal category
                  [35,100,210,5]) # high

array([ 21,  97, 193,   3])

In [33]:
np.random.normal(3, 2.5, size=(2, 4))

array([[ 2.90046559,  1.97274556,  3.00612089,  4.78802312],
       [ 1.64536699, -1.14265069,  2.0386687 ,  8.48579362]])

In [34]:
np.random.normal(size=(3,4))

array([[ 0.35349826,  0.38491728, -0.02816897,  0.08503587],
       [-1.61432245,  0.21786398,  0.20526926,  0.19776813],
       [ 0.25974361,  0.77833595,  1.17318868,  0.89362183]])