In [1]:
import numpy as np

In [2]:
print(np.array_equal([1, 2], [1, 2]))

print(np.array_equal(np.array([1, 2]), np.array([1, 2])))

print(np.array_equal([1, 2], [1, 2, 3]))

print(np.array_equal([1, 2], [1, 4]))

True
True
False
False


In [13]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
b = a > 4
b

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
print(a[a < 5])

[1 2 3 4]


In [15]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [16]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [17]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [7]:
arr = np.random.randint(20,80, size=(3,2,5))
arr

array([[[49, 33, 51, 67, 20],
        [23, 33, 47, 64, 43]],

       [[71, 51, 37, 31, 68],
        [27, 34, 66, 76, 67]],

       [[30, 43, 53, 76, 35],
        [36, 40, 73, 64, 38]]])

In [8]:
np.all(arr < 50, axis=0)

array([[False, False, False, False, False],
       [ True,  True, False, False, False]])

In [9]:
np.any(arr < 50, axis=0)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True]])

In [10]:
np.alltrue(arr < 50, axis=0)  # same as np.all

array([[False, False, False, False, False],
       [ True,  True, False, False, False]])

In [12]:
np.argwhere(arr>60)

array([[0, 0, 3],
       [0, 1, 3],
       [1, 0, 0],
       [1, 0, 4],
       [1, 1, 2],
       [1, 1, 3],
       [1, 1, 4],
       [2, 0, 3],
       [2, 1, 2],
       [2, 1, 3]], dtype=int64)

In [20]:
names = np.array(["Taha", "Pınar", "Azra", "Taha"])
data = np.random.randn(4,3)

data[names=="Taha"]

array([[-0.21127531, -2.90511227,  0.47072778],
       [ 2.38396619, -0.12042958,  0.74689635]])

In [21]:
data[names=="Taha",1:]

array([[-2.90511227,  0.47072778],
       [-0.12042958,  0.74689635]])

In [22]:
data[~(names=="Taha")]

array([[ 0.37419089,  0.81395182, -0.70819122],
       [ 0.00838907, -0.61359528, -1.5443799 ]])

In [23]:
choose = (names=="Taha") | (names=="Azra")
data[choose]

array([[-0.21127531, -2.90511227,  0.47072778],
       [ 0.00838907, -0.61359528, -1.5443799 ],
       [ 2.38396619, -0.12042958,  0.74689635]])

In [24]:
data[data<0]=0 
data

array([[0.        , 0.        , 0.47072778],
       [0.37419089, 0.81395182, 0.        ],
       [0.00838907, 0.        , 0.        ],
       [2.38396619, 0.        , 0.74689635]])