In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.2'

In [ ]:
np?

<img src="numpy_basics.png" width="800" height="400">

In [11]:
my_list = [1,2,3,4,5,6]
my_list

[1, 2, 3, 4, 5, 6]

In [12]:
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5, 6])

In [13]:
print(my_array)

[1 2 3 4 5 6]


In [14]:
type(my_array)

numpy.ndarray

In [15]:
print(type(my_array))

<class 'numpy.ndarray'>


In [8]:
arr = np.array([x**2 for x in range(1, 8)])
arr

array([ 1,  4,  9, 16, 25, 36, 49])

In [9]:
mix = np.array([1, 2, 4, "Jack", True, 2.5])
mix

array(['1', '2', '4', 'Jack', 'True', '2.5'], dtype='<U32')

In [16]:
my_array

array([1, 2, 3, 4, 5, 6])

In [22]:
# ndarray.dtype: an object describing the type of the elements in the array.

my_array.dtype

dtype('int32')

In [23]:
# ndarray.ndim: the number of axes (dimensions) of the array.

my_array.ndim
# np.ndim(arr)

1

In [24]:
# ndarray.size: the total number of elements of the array. 

my_array.size
# np.size(arr)

6

In [42]:
np.alen(my_array) # Return the length of the first dimension of the input

6

In [25]:
# ndarray.shape: the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.

np.shape(my_array)
# arr.shape

(6,)

In [26]:
# ndarray.itemsize: the size in bytes of each element of the array.

my_array.itemsize

4

In [27]:
# ndarray.data: the buffer containing the actual elements of the array.

my_array.data

In [28]:
arr = np.array([[1., 0., 0.],[0., 1., 2.]])
arr

array([[1., 0., 0.],
       [0., 1., 2.]])

In [29]:
arr.dtype

dtype('float64')

In [30]:
np.ndim(arr)

2

In [31]:
arr.size

6

In [44]:
np.alen(arr)

2

In [32]:
arr.shape

(2, 3)

In [33]:
arr.itemsize

8

In [34]:
arr2 = np.array([[[1,2,3,4],[1,7,3,6],[8,3,4,5]],[[1,2,7,4],[9,5,3,4],[2,6,4,5]]])
arr2

array([[[1, 2, 3, 4],
        [1, 7, 3, 6],
        [8, 3, 4, 5]],

       [[1, 2, 7, 4],
        [9, 5, 3, 4],
        [2, 6, 4, 5]]])

In [50]:
np.unique(arr2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr2.ndim

3

In [36]:
arr2.size

24

In [39]:
np.size(arr, axis=0)

2

In [41]:
np.size(arr, axis=1)

3

In [43]:
np.alen(arr)  # Return the length of the first dimension of the input

2

In [37]:
arr2.shape

(2, 3, 4)

In [45]:
a = np.array(['clarusway', 'data', 'science', 'bootcamp', 'is', 'the', 'best'], dtype = str)
print('Capitalized: ', np.char.capitalize(a))
print('Lowered: ', np.char.lower(a))
print('Uppered: ', np.char.upper(a))
print('Swapcased: ', np.char.swapcase(a))
print('Titlecased: ', np.char.title(a))

Capitalized:  ['Clarusway' 'Data' 'Science' 'Bootcamp' 'Is' 'The' 'Best']
Lowered:  ['clarusway' 'data' 'science' 'bootcamp' 'is' 'the' 'best']
Uppered:  ['CLARUSWAY' 'DATA' 'SCIENCE' 'BOOTCAMP' 'IS' 'THE' 'BEST']
Swapcased:  ['CLARUSWAY' 'DATA' 'SCIENCE' 'BOOTCAMP' 'IS' 'THE' 'BEST']
Titlecased:  ['Clarusway' 'Data' 'Science' 'Bootcamp' 'Is' 'The' 'Best']
