In [1]:
import numpy as np

In [ ]:
# axis 1 = y axis, column, feature
# axis 0 = x axis, row, observation

### <i><b>numpy.append:
    
.append values to the end of an array.

In [16]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9], axis=0)
# ValueError: all the input arrays must have same number of dimensions, 
# but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [18]:
arr1 = np.random.randint(20,80, size=(3,3))
arr1

array([[54, 25, 74],
       [45, 54, 28],
       [69, 75, 62]])

In [19]:
arr2 = np.ones((1,3)) * 5
arr2

array([[5., 5., 5.]])

In [20]:
np.append(arr1, arr2)

array([54., 25., 74., 45., 54., 28., 69., 75., 62.,  5.,  5.,  5.])

In [21]:
np.append(arr1, arr2, axis=0)

array([[54., 25., 74.],
       [45., 54., 28.],
       [69., 75., 62.],
       [ 5.,  5.,  5.]])

In [ ]:
np.append(arr1, arr2, axis=1)
# ValueError

In [22]:
np.append(arr1, [[5, 5, 5], [5,5,5], [5,5,5]], axis=1)

array([[54, 25, 74,  5,  5,  5],
       [45, 54, 28,  5,  5,  5],
       [69, 75, 62,  5,  5,  5]])

### <i><b>numpy.concatenate:
    
.Join a sequence of arrays along an existing axis.

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [5]:
np.concatenate((a, b))  # default axis is 0.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.concatenate((a, b), axis=1)
# ValueError: all the input array dimensions for the concatenation axis must match exactly

In [26]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [27]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [8]:
np.concatenate(([[1, 2], [3, 4]], [[5, 6], [7, 8]]), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### <i><b>numpy.vstack():
. Stack arrays in sequence vertically (row wise).

### <i><b>numpy.hstack():
. Stack arrays in sequence horizontally (column wise).

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [32]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [35]:
c = np.array([[1], [2], [3]])
d = np.array([[4], [5], [6]])

In [36]:
np.vstack((c,d))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [37]:
np.hstack((c,d))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
# vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print()
print(np.vstack([v1,v2,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]


In [51]:
# horizontally stacking vectors

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack([h1,h2]))
print()
print(np.hstack([h1,h2,h2,h2]))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]

[[1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]]


### <i><b>numpy.hsplit():
. Split an array into multiple sub-arrays horizontally (column-wise).

### <i><b>numpy.vsplit():
. Split an array into multiple sub-arrays vertically (row-wise).
    
### <i><b>numpy.split():
. Split an array into multiple sub-arrays as views into ary.

In [44]:
arr = np.arange(30).reshape(2, 15)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [45]:
new_arr = np.hsplit(new, 3)
new_arr

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [46]:
new_arr[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [48]:
new_arr2 = np.vsplit(new, 2)
new_arr2

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [49]:
new_arr2[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [3]:
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [4]:
x = np.arange(7.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.])]

In [5]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.array_split(a, 2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]])]

In [7]:
np.split(np.arange(10,34).reshape(8,3), 4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [9]:
concat = np.arange(1,26).reshape(5,5)
concat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
np.split(concat,[1,3])

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])]

In [11]:
np.split(concat,[2,3],axis=1)

[array([[ 1,  2],
        [ 6,  7],
        [11, 12],
        [16, 17],
        [21, 22]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23]]),
 array([[ 4,  5],
        [ 9, 10],
        [14, 15],
        [19, 20],
        [24, 25]])]