In [1]:
import numpy as np

In [ ]:
# axis 1 = y axis, column, feature
# axis 0 = x axis, row, observation

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [3]:
arr[0,:2]

array([1, 2])

In [4]:
arr[1,2]

6

In [6]:
arr[0:2,2]

array([3, 6])

In [5]:
arr[-1]

array([7, 8, 9])

In [7]:
arr[-1, 0:2]

array([7, 8])

In [8]:
arr[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [9]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [10]:
arr[:,:1]

array([[1],
       [4],
       [7]])

In [12]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [10]:
rand_float = np.random.rand(5,5)
rand_float

array([[0.76980521, 0.99937447, 0.49710257, 0.59072714, 0.49232528],
       [0.06771073, 0.35937273, 0.57267236, 0.01256521, 0.86552682],
       [0.68017752, 0.20394305, 0.56171704, 0.90919584, 0.18411602],
       [0.48775977, 0.52992059, 0.05006548, 0.47982896, 0.17357555],
       [0.98812364, 0.83433945, 0.47222343, 0.10740715, 0.10334256]])

In [11]:
rand_float[0]

array([0.76980521, 0.99937447, 0.49710257, 0.59072714, 0.49232528])

In [12]:
rand_float[1:4]

array([[0.06771073, 0.35937273, 0.57267236, 0.01256521, 0.86552682],
       [0.68017752, 0.20394305, 0.56171704, 0.90919584, 0.18411602],
       [0.48775977, 0.52992059, 0.05006548, 0.47982896, 0.17357555]])

In [13]:
rand_float[-4:-2]

array([[0.06771073, 0.35937273, 0.57267236, 0.01256521, 0.86552682],
       [0.68017752, 0.20394305, 0.56171704, 0.90919584, 0.18411602]])

In [14]:
rand_float[:, 0]

array([0.76980521, 0.06771073, 0.68017752, 0.48775977, 0.98812364])

In [15]:
rand_float[0:2, 0:3]

array([[0.76980521, 0.99937447, 0.49710257],
       [0.06771073, 0.35937273, 0.57267236]])

In [16]:
rand_float[0:2,1]

array([0.99937447, 0.35937273])

In [17]:
rand_float[0, ::2]

array([0.76980521, 0.49710257, 0.49232528])

In [18]:
rand_float[:,0].reshape(-1,1)

array([[0.76980521],
       [0.06771073],
       [0.68017752],
       [0.48775977],
       [0.98812364]])

In [19]:
rand_float[0][1:4]

array([0.99937447, 0.49710257, 0.59072714])

In [20]:
rand_float[1][1:4]

array([0.35937273, 0.57267236, 0.01256521])

## Fancy Indexing

In [21]:
fancy = np.random.randint(0,100,10)
fancy

array([65,  2,  3,  7, 76, 30, 38, 72, 62, 57])

In [22]:
fancy[2:4]

array([3, 7])

In [23]:
fancy[[3,5,1,9]]

array([ 7, 30,  2, 57])

In [24]:
fancy[0] = 44
fancy

array([44,  2,  3,  7, 76, 30, 38, 72, 62, 57])

In [25]:
f1 = fancy[[3,5,1,9]]
f1

array([ 7, 30,  2, 57])

In [26]:
f1[0] = -1
f1

array([-1, 30,  2, 57])

In [27]:
fancy

array([44,  2,  3,  7, 76, 30, 38, 72, 62, 57])

In [28]:
fancy2 = fancy
fancy2

array([44,  2,  3,  7, 76, 30, 38, 72, 62, 57])

In [29]:
fancy2[1] = 111
fancy2

array([ 44, 111,   3,   7,  76,  30,  38,  72,  62,  57])

In [30]:
fancy3 = fancy.copy()
fancy3

array([ 44, 111,   3,   7,  76,  30,  38,  72,  62,  57])

In [31]:
fancy3[0] = 11111111
fancy3

array([11111111,      111,        3,        7,       76,       30,
             38,       72,       62,       57])

In [32]:
fancy

array([ 44, 111,   3,   7,  76,  30,  38,  72,  62,  57])

In [33]:
fancy[3:7] = 100
fancy

array([ 44, 111,   3, 100, 100, 100, 100,  72,  62,  57])

In [38]:
x = np.array([[3.95, 3.98, 2.43],
              [3.89, 3.84, 2.31],
              [4.05, 4.07, 2.31],
              [4.2 , 4.23, 2.63],
              [4.34, 4.35, 2.75],
              [3.94, 3.96, 2.48],
              [3.95, 3.98, 2.47],
              [4.07, 4.11, 2.53]])

In [39]:
x[2:6,1:]

array([[4.07, 2.31],
       [4.23, 2.63],
       [4.35, 2.75],
       [3.96, 2.48]])

In [40]:
x[2:6,1:] = 0
x

array([[3.95, 3.98, 2.43],
       [3.89, 3.84, 2.31],
       [4.05, 0.  , 0.  ],
       [4.2 , 0.  , 0.  ],
       [4.34, 0.  , 0.  ],
       [3.94, 0.  , 0.  ],
       [3.95, 3.98, 2.47],
       [4.07, 4.11, 2.53]])

In [41]:
x[2:6,1:] = [-1,5]
x

array([[ 3.95,  3.98,  2.43],
       [ 3.89,  3.84,  2.31],
       [ 4.05, -1.  ,  5.  ],
       [ 4.2 , -1.  ,  5.  ],
       [ 4.34, -1.  ,  5.  ],
       [ 3.94, -1.  ,  5.  ],
       [ 3.95,  3.98,  2.47],
       [ 4.07,  4.11,  2.53]])

In [42]:
x[x>3]

array([3.95, 3.98, 3.89, 3.84, 4.05, 5.  , 4.2 , 5.  , 4.34, 5.  , 3.94,
       5.  , 3.95, 3.98, 4.07, 4.11])