In [1]:
import numpy as np

In [ ]:
# axis 1 = y axis, column, feature
# axis 0 = x axis, row, observation

In [33]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [14]:
a+b

array([ 6,  8, 10, 12])

In [15]:
a-a

array([0, 0, 0, 0])

In [34]:
np.subtract(b,a)

array([4, 4, 4, 4])

In [35]:
np.divide(b,a)

array([5.        , 3.        , 2.33333333, 2.        ])

In [16]:
a*b

array([ 5, 12, 21, 32])

In [17]:
a*100

array([100, 200, 300, 400])

In [18]:
1/a

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [19]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,9]])
b1 = np.array([[2,3,4,5],[1,2,4,5],[1,2,3,4]])

In [20]:
a1.size, b1.size

(12, 12)

In [21]:
a1+b1

array([[ 3,  5,  7,  9],
       [ 6,  8, 11, 13],
       [ 3,  6,  9, 13]])

In [22]:
a1*b1

array([[ 2,  6, 12, 20],
       [ 5, 12, 28, 40],
       [ 2,  8, 18, 36]])

In [25]:
arr1 = np.arange(9.0).reshape(3,3)
arr1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [30]:
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.add(arr1,arr2)  # same as arr1 + arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [32]:
arr3 = np.arange(3.0)
arr3

array([0., 1., 2.])

In [33]:
np.add(arr1,arr3)  # same as arr1 + arr3

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [ ]:
# np.mod / np.remainder : Return element-wise remainder of division. 
# It is equivalent to the Python modulus operator "x1 % x2"

In [27]:
arr = np.random.randint(2, 18, 7)
arr

array([ 2,  3,  9, 14,  5, 10,  4])

In [28]:
np.mod(arr, 3)

array([2, 0, 0, 2, 2, 1, 1], dtype=int32)

In [29]:
np.remainder([4, 7], [2, 3])

array([0, 1], dtype=int32)

In [ ]:
# np.abs (np.absolute)

In [4]:
arr = np.random.randn(3,4)

In [5]:
arr

array([[-0.50723287, -1.65751299, -0.55181228,  2.66686596],
       [ 0.02778049,  0.75373507, -0.33773136, -0.19401178],
       [-0.3144896 ,  0.00280797, -2.50959534,  0.06247252]])

In [6]:
# np.abs(arr)
np.absolute(arr)

array([[0.50723287, 1.65751299, 0.55181228, 2.66686596],
       [0.02778049, 0.75373507, 0.33773136, 0.19401178],
       [0.3144896 , 0.00280797, 2.50959534, 0.06247252]])

In [7]:
compl = ([2+3j,2-4j,-4-5j])

# np.abs(compl)
np.absolute(compl)

array([3.60555128, 4.47213595, 6.40312424])

In [2]:
print(np.around([0.37, 1.64]))

print(np.around([0.37, 1.64], decimals=1))

print(np.around([.5, 1.5, 2.5, 3.5, 4.5])) # rounds to nearest even value when .5

print(np.around([1,2,3,11], decimals=1)) # ndarray of ints is returned

print(np.around([1,2,3,11], decimals=-1))

[0. 2.]
[0.4 1.6]
[0. 2. 2. 4. 4.]
[ 1  2  3 11]
[ 0  0  0 10]


In [9]:
nums = np.random.randint(2,20, size=(3,5))
nums

array([[14,  6,  9,  4, 12],
       [10, 18,  9, 10, 16],
       [ 7, 12, 15,  5,  2]])

In [10]:
np.max(nums)

18

In [11]:
np.min(nums)

2

In [12]:
np.sum(nums)  # == nums.sum()

149

In [22]:
np.sum(nums, axis=0)

array([31, 36, 33, 19, 30])

In [13]:
np.max(nums, axis=0)

array([14, 18, 15, 10, 16])

In [14]:
np.max(nums, axis=1)

array([14, 18, 15])

In [15]:
np.min(nums, axis=0)

array([7, 6, 9, 4, 2])

In [16]:
np.amax(nums)

18

In [17]:
np.amax(nums, axis=1)

array([14, 18, 15])

In [18]:
np.amin(nums, axis=1)

array([4, 9, 2])

In [19]:
nums.argmax()

6

In [20]:
nums.argmin()

14

In [21]:
np.argmin(nums, axis=0)

array([2, 0, 0, 0, 2], dtype=int64)

In [24]:
seq = np.arange(12).reshape(3,4)
seq

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
np.power(seq, 2)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [28]:
np.square(seq)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [26]:
np.power(seq, 0.5)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [27]:
np.sqrt(seq)
# np.sqrt: Return the non-negative square-root of an array, element-wise.

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [29]:
data = np.arange(6).reshape((3,2))
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [30]:
np.average(data)

2.5

In [17]:
np.average(data, axis=1, weights=[1./4, 3./4])

array([0.75, 2.75, 4.75])

In [ ]:
np.average(data, axis=0, weights=[1./4, 3./4])
# ValueError: Length of weights not compatible with specified axis.

In [31]:
arr = np.random.rand(3,2)  # random samples from a "uniform distribution" over [0, 1)
arr

array([[0.26038521, 0.33197462],
       [0.18867981, 0.81073768],
       [0.83582288, 0.6898112 ]])

In [32]:
arr.mean()  # average

0.5195685663930013

In [33]:
np.average(arr)

0.5195685663930013

In [34]:
print(arr.mean(1))   # rows average
print(arr.mean(0))   # columns average

[0.29617991 0.49970874 0.76281704]
[0.42829597 0.61084117]


In [35]:
arr.std()  # standard deviation

0.2663436585900821

In [36]:
arr.var()  # variance

0.07093894447115019

In [37]:
np.median(arr)

0.5108929100448245

In [38]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [21]:
np.square(arr_2)

array([ 4,  9, 16, 25, 36], dtype=int32)

In [24]:
arrayOne = np.array([[5, 6, 9], [11 ,18, 8]])
arrayTwo = np.array([[15 ,22, 3], [4 ,7, 1]])

np.square(np.add(arrayOne, arrayTwo))

array([[400, 784, 144],
       [225, 625,  81]], dtype=int32)

In [39]:
arr_2

array([2, 3, 4, 5, 6])

In [40]:
np.sin(arr_2)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [41]:
np.sin(np.pi)

1.2246467991473532e-16

In [42]:
np.sin(np.pi/2)

1.0

In [43]:
np.cos(arr_2)

array([-0.41614684, -0.9899925 , -0.65364362,  0.28366219,  0.96017029])

In [44]:
np.log(10)

2.302585092994046

In [17]:
# numpy.exp : Calculate the exponential of all elements in the input array.
np.exp(np.array([1,2,3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [18]:
np.log(np.exp(1))

1.0

In [64]:
np.angle([1.0, 1.0j, 1+1j])  # in radians
# Return the angle of the complex argument

array([0.        , 1.57079633, 0.78539816])

In [65]:
np.angle(1+1j, deg=True)  # in degrees

45.0

In [ ]:
# linear algebra
# np.matmul : Matrix product of two arrays.

In [45]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [47]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [87]:
# find determinant 
# (Determinant, kare matrisleri bir reel sayıya eşleyen fonksiyondur. 
# Determinant fonksiyonun kare matrisi eşlediği o sayıya matrisin determinantı denir.)

c = np.identity(3)
np.linalg.det(c)

1.0

In [76]:
a = np.array([[1,2],[3,4]])      
b = np.array([[5,6],[7,8]]) 
np.dot(a,b)
# array :(1*5)+(2*7)=19   (1*6)+(2*8)=22   (3*5)+(4*7)=43   (3*6)+(4*8)=50

array([[19, 22],
       [43, 50]])

In [68]:
seq = np.arange(8).reshape(2,4)
seq

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [70]:
seq.transpose()

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [71]:
np.dot(seq.T,seq)

array([[16, 20, 24, 28],
       [20, 26, 32, 38],
       [24, 32, 40, 48],
       [28, 38, 48, 58]])

In [72]:
ss = np.array([[1, 2], [3, 4]])
tt = np.array([[5, 6], [7, 8]])

In [73]:
ss+tt

array([[ 6,  8],
       [10, 12]])

In [74]:
ss.dot(tt)

array([[19, 22],
       [43, 50]])

In [75]:
tt.dot(ss)

array([[23, 34],
       [31, 46]])