In [1]:
import numpy as np

In [ ]:
# axis 1 = y axis, column, feature
# axis 0 = x axis, row, observation

### <b><i>numpy.sort():</b> 
    
. Return a sorted copy of an array.


### <b><i>numpy.argsort():</b> 
    
. Returns the indices that would sort an array.

In [11]:
arr1 = np.array([2,1,5,3,7,4,6,8])
arr2 = np.array([[1,4,2],[3,1,5]])
arr3 = np.array([[47,35,73],[82,22,12],[53,94,66]])

In [ ]:
# The default axis is -1, which sorts along the last axis.

In [12]:
np.sort(arr1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.sort(arr2) 

array([[1, 2, 4],
       [1, 3, 5]])

In [14]:
np.sort(arr3)

array([[35, 47, 73],
       [12, 22, 82],
       [53, 66, 94]])

In [15]:
arr2

array([[1, 4, 2],
       [3, 1, 5]])

In [16]:
arr2.sort(0)
arr2

array([[1, 1, 2],
       [3, 4, 5]])

In [17]:
np.sort(arr2, axis=0)   # sort along the first axis

array([[1, 1, 2],
       [3, 4, 5]])

In [19]:
np.sort(arr3, axis=0)

array([[47, 22, 12],
       [53, 35, 66],
       [82, 94, 73]])

In [18]:
np.sort(arr2, axis=None)   # sort the flattened array

array([1, 1, 2, 3, 4, 5])

In [24]:
arr1 = np.array([2,1,5,3,7,4,6,8])
arr2 = np.array([[1,4,2],[3,1,5]])
arr3 = np.array([[47,35,73],[82,22,12],[53,94,66]])

In [25]:
np.argsort(arr1)

array([1, 0, 3, 5, 2, 6, 4, 7], dtype=int64)

In [26]:
np.argsort(arr2)

array([[0, 2, 1],
       [1, 0, 2]], dtype=int64)

In [28]:
np.argsort(arr2, axis=0)

array([[0, 1, 0],
       [1, 0, 1]], dtype=int64)

In [27]:
np.argsort(arr3)

array([[1, 0, 2],
       [2, 1, 0],
       [0, 2, 1]], dtype=int64)

In [32]:
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
arr

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [33]:
sorted_column = arr[np.argsort(arr[:, 1])]
sorted_column

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

In [34]:
np.argsort(arr[1, :])

array([2, 1, 0], dtype=int64)

In [35]:
sorted_row = arr[:, np.argsort(arr[1, :])]
sorted_row

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [36]:
np.argsort(arr[:, 1])

array([1, 0, 2], dtype=int64)

In [38]:
arr

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [37]:
list(reversed(arr))

[array([53, 94, 66]), array([82, 22, 12]), array([34, 43, 73])]

In [ ]:
# apply_along_axis
# apply_over_axis

In [41]:
def my_func(a):
   """Average first and last element of a 1-D array"""
   return (a[0] + a[-1]) * 0.5

b = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(np.apply_along_axis(my_func, 0, b))
print(np.apply_along_axis(my_func, 1, b))

[4. 5. 6.]
[2. 5. 8.]


In [42]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 1, b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

In [43]:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 0, b)

array([[4, 1, 6],
       [5, 2, 7],
       [8, 3, 9]])

In [44]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
np.apply_over_axes(np.sum, arr, [0,2])

array([[[ 60],
        [ 92],
        [124]]])

In [46]:
# Tuple axis arguments to ufuncs are equivalent:

np.sum(arr, axis=(0,2), keepdims=True)

array([[[ 60],
        [ 92],
        [124]]])