In [1]:
import numpy as np

In [2]:
arr = np.arange(24).reshape(4,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [3]:
np.save("numbers", arr)  # We saved it in the working directory as .npy extension

In [4]:
np.load("numbers.npy")

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
filedata = np.genfromtxt('numbers.txt', delimiter=',') 
filedata

array([[ 13.,  14.,  22.,  88., 159.,   7.,  25.,  11.,   9.,  10.],
       [ 22.,  89., 456.,  23.,   5.,   7.,  15., 155.,  78.,   9.],
       [ 88.,  77.,  66., 555., 444.,  12.,   0.,   3., 254.,   2.]])

In [6]:
filedata = np.genfromtxt('numbers.txt', delimiter=',') # 10*10 olduğu için hata vermedi
filedata = filedata.astype("int32") # alan daraldı, çünkü noktalar gitti
print(filedata)

[[ 13  14  22  88 159   7  25  11   9  10]
 [ 22  89 456  23   5   7  15 155  78   9]
 [ 88  77  66 555 444  12   0   3 254   2]]
