In [1]:
import numpy as np

In [86]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [96]:
a[np.newaxis, :]

array([[0, 1, 2, 3, 4, 5]])

In [97]:
a[np.newaxis, :].shape

(1, 6)

In [98]:
np.expand_dims(a, axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [93]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [95]:
a[:, np.newaxis].shape

(6, 1)

In [99]:
np.expand_dims(a, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [125]:
arr = np.arange(16).reshape(2,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [126]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

### <i><b>numpy.reshape:
.Gives a new shape to an array without changing its data.

In [5]:
arr = np.arange(72).reshape(2,3,2,6)
arr

array([[[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],

        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]]],


       [[[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]],

        [[48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59]],

        [[60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]]]])

In [6]:
print(np.size(arr))

print(np.size(arr, axis=0))
print(np.size(arr, axis=1))
print(np.size(arr, axis=2))
print(np.size(arr, axis=3))

72
2
3
2
6


In [7]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a.shape

(3, 2)

In [59]:
x = np.arange(1, 7).reshape(2, 3)
x.dtype

dtype('int32')

In [8]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.reshape(arr, 6)

array([1, 2, 3, 4, 5, 6])

In [12]:
np.reshape(arr, -1)

array([1, 2, 3, 4, 5, 6])

In [14]:
np.reshape(arr, (3,-1))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
np.reshape(arr, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [117]:
seq = np.arange(16).reshape(4,4)
seq

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
print("".join(str(seq)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


### <i><b>numpy.diag(): 
. Extract a diagonal or construct a diagonal array.

In [104]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
np.diag(x)

array([1, 5, 9])

In [106]:
np.diag(np.diag(x))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [107]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [108]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

### <i><b>numpy.ravel: 
. Return a contiguous flattened array.

In [45]:
x = np.array([[[4, 5, 6], [1, 2, 3]], [[7, 8, 9], [10, 11, 12]]])
x

array([[[ 4,  5,  6],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
np.ravel(x)

array([ 4,  5,  6,  1,  2,  3,  7,  8,  9, 10, 11, 12])

In [47]:
x.reshape(-1)

array([ 4,  5,  6,  1,  2,  3,  7,  8,  9, 10, 11, 12])

In [48]:
np.ravel(x, order='F')

array([ 4,  7,  1, 10,  5,  8,  2, 11,  6,  9,  3, 12])

In [49]:
np.ravel(x, order='C')

array([ 4,  5,  6,  1,  2,  3,  7,  8,  9, 10, 11, 12])

In [51]:
np.ravel(x, order='K')

array([ 4,  5,  6,  1,  2,  3,  7,  8,  9, 10, 11, 12])

In [37]:
y1 = np.arange(12).reshape(2,3,2)
y1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [39]:
y2= y1.swapaxes(1,2)
y2

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [40]:
y1.ravel(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
y2.ravel(order='C')

array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])

In [44]:
y2.ravel(order='K')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### <i><b>ndarray.flatten()
    
. Return a copy of the array collapsed into one dimension. Default order is 'C'

In [52]:
xx = np.array([[1, 2], [3, 4], [5, 6]])
print(xx.flatten())
print(xx.ravel())
print(xx.reshape(-1))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [53]:
xx.flatten('F')

array([1, 3, 5, 2, 4, 6])

### <i><b>ndarray.flat()

. A 1-D iterator over the array.

In [111]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
x.flat[3]

4

In [63]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
x.T.flat[3]

5

In [65]:
type(x.flat)

numpy.flatiter

In [ ]:
# assignment with flat

In [66]:
x.flat = 3; x

array([[3, 3, 3],
       [3, 3, 3]])

In [67]:
x.flat[[1,4]] = 1; x

array([[3, 1, 3],
       [3, 1, 3]])

In [68]:
for i in x.flat:
  print(i, end="")

313313

In [85]:
for i in np.nditer(x):
  print(i, end="")

313313

In [115]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
for row in x:
    print(row)

[1 2 3]
[4 5 6]


In [113]:
for cell in x.flat:
    print(cell)

1
2
3
4
5
6


### <i><b> numpy.flip, numpy.flipud, numpy.fliplr

. numpy.flip(m, axis=None) : Reverse the order of elements in an array along the given axis.
    
. numpy.flipud(m) : Reverse the order of elements along axis 0 (up/down).
    
. numpy.fliplr(m) : Reverse the order of elements along axis 1 (left/right).

In [70]:
arr = np.arange(8).reshape((2,2,2))
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [71]:
np.flip(arr)

array([[[7, 6],
        [5, 4]],

       [[3, 2],
        [1, 0]]])

In [73]:
np.flip(arr, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [74]:
np.flip(arr, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [75]:
np.flip(arr, (0, 2))

array([[[5, 4],
        [7, 6]],

       [[1, 0],
        [3, 2]]])

In [76]:
np.flipud(arr)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [84]:
arr[::-1]

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [82]:
np.flipud([[1,2,3], [4,5,6]])

array([[4, 5, 6],
       [1, 2, 3]])

In [79]:
np.fliplr(arr)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [81]:
np.fliplr([[1,2,3], [4,5,6]])

array([[3, 2, 1],
       [6, 5, 4]])